---
title: 'Archive and share your package'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

-   How do you archive a publication package?
-   Which parts of the package do I need to publish?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

-   Determine which parts of the package need to be published and which parts need to be archived internally

::::::::::::::::::::::::::::::::::::::::::::::::

## Introduction

Now that you have created a publication package, you need to archive it in a place where it will be accessible for the long term.
For this reason, it should not be on your hard disk or another personal storage space.
At EUR, the Yoda Vault is suitable for long-term archiving of your package.
In addition, you should determine which parts of the package you want to publish publicly or under restricted access conditions (in line with the adagium: as open as possible, as closed as necessary)

::::::::::::::::::::::::::::::::::::: keypoints 

- Use `.md` files for episodes when you want static content
- Use `.Rmd` files for episodes when you need to generate output
- Run `sandpaper::check_lesson()` to identify any issues with your lesson
- Run `sandpaper::build_lesson()` to preview your lesson locally

::::::::::::::::::::::::::::::::::::::::::::::::

