---
title: 'Prepare your package - I. Documentation'
teaching: 5
exercises: 0
---

::: questions
-   Which documents are needed in a publication package for my research project?
-   How do I document my package in such a way that is understandable for others?
:::

::: objectives
-   Assign all relevant research documentation to the publication package of your own research project
-   Apply best practices for file names and file formats in your publication package
:::

Instead of chronologically adding the components according to their numbering in the [list of publication package components](introduction.Rmd##the-contents-of-a-publication-package), we will first gather all documentation that is needed for your package in this part of the workshop. Hopefully, most of these documents are already available somewhere on your system (except probably for the readme file). In that case, you can quickly start building your package by gathering those files, perhaps focusing mostly on improving file names and file formats.

## Project folder

First, we need a place to save all the components of the publication package in one place.

::: checklist
#### Steps to take

-   Create a folder with a clear name for the research project (use the [three principles for file naming described in this presentation](https://doi.org/10.5281/zenodo.7551576){target="_blank"})
-   Optionally, you can create a small folder structure with sub folders if you prefer (for exampl, such as used in the [EUR publication package example](https://doi.org/10.5281/zenodo.7956600){target="_blank"})
:::


::: keypoints
-   Add sufficient documentation to the publication package in the form of a data management plan, manuscript, readme file, and ethics documentation
-   Save the files using clear file names and in sustainable file formats

:::
